---
# File: binaries.yml
# Part: nodejs
#
# Description: Installs nodejs from binaries
#
# Parameters - Must be definied in playbook:
#   - nodejs_version = The wanted version of node to be installed

- name: Make sure that the directory to hold the node.js binaries exists
  file:
    path: /usr/local/nodejs
    state: directory
    recurse: yes
    mode: 0755

- name: Fetching node.js binaries from http://nodejs.org/
  get_url:
    url: "http://nodejs.org/dist/v{{nodejs_version}}/node-v{{nodejs_version}}-{{nodejs_flavor}}.tar.gz"
    dest: "/tmp/"

- name: Unpack node.js tarball
  command: tar zxf node-v{{nodejs_version}}-{{nodejs_flavor}}.tar.gz chdir=/tmp

- name: Move to /usr/local/nodejs
  shell: rm -rf /usr/local/nodejs/node-v{{nodejs_version}}-{{nodejs_flavor}} && mv /tmp/node-v{{nodejs_version}}-{{nodejs_flavor}} /usr/local/nodejs/node-v{{nodejs_version}}-{{nodejs_flavor}}

- name: Update the symbolic link to the node.js install
  file:
    path: /usr/local/nodejs/default
    src: "/usr/local/nodejs/node-v{{nodejs_version}}-{{nodejs_flavor}}"
    state: link
    force: yes

- name: Add the node.js binary to the system path
  lineinfile: "{{item}}"
  with_items:
    - dest=/etc/profile regexp='^NODE_HOME=/usr/local/nodejs/default' line="NODE_HOME=/usr/local/nodejs/default" state=present
    - dest=/etc/profile regexp='^PATH=.*NODE_HOME.*' line="PATH=$PATH:$NODE_HOME/bin" state=present

- name: Inform the system where node is located and set this one as the default
  shell: "{{item}}"
  with_items:
    - 'update-alternatives --install "/usr/bin/node" "node" "/usr/local/nodejs/default/bin/node" 1'
    - 'update-alternatives --set node /usr/local/nodejs/default/bin/node'

- name: Inform the system where npm is located and set this one as the default
  shell: "{{item}}"
  with_items:
    - 'update-alternatives --install "/usr/bin/npm" "npm" "/usr/local/nodejs/default/bin/npm" 1'
    - 'update-alternatives --set npm /usr/local/nodejs/default/bin/npm'
