# file: nodejs/tasks/main.yml

- name: Check if the node version is already installed
  command: node --version
  ignore_errors: yes
  register: node_version
  changed_when: node_version.rc != 0 or node_version.stdout != "v{{ nodejs_version }}"

- include: package.yml
  when: nodejs_install_method == "package" and node_version.changed

- include: binaries.yml
  when: nodejs_install_method == "binaries" and node_version.changed

- include: source.yml
  when: nodejs_install_method == "source" and node_version.changed
