# file: nodejs/tasks/main.yml

- include: package.yml
  when: nodejs_install_method == "package"

- name: Check if the node version is already installed
  command: "{{nodejs_binary_prefix}}/bin/node --version"
  ignore_errors: yes
  register: node_version
  changed_when: node_version.rc != 0 or node_version.stdout.find(nodejs_version) < 0
  when: nodejs_install_method == "binary"

- name: Check if the node version is already installed
  command: "{{nodejs_directory}}/node-v{{nodejs_version}}/bin/node --version"
  ignore_errors: yes
  register: node_version
  changed_when: node_version.rc != 0 or node_version.stdout.find(nodejs_version) < 0
  when: nodejs_install_method == "source"

- include: source.yml
  when: nodejs_install_method == "source" and node_version.changed

- include: binary.yml
  when: nodejs_install_method == "binary" and node_version.changed
