---
- name: "Make sure the ansible required dependencies are installed"
  apt:
    pkg: python-pycurl
    state: present

- name: "add signing key"
  apt_key:
    url: "{{nodejs_apt_key_url}}"
    id: "{{nodejs_apt_key}}"
    state: present

- name: "Set amd64 arch"
  set_fact:
    nodejs_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: "add sources.list entry"
  lineinfile:
    dest: /etc/apt/sources.list.d/nodesource.list
    create: yes
    line: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/{{node_{{node_version|split('.')[0]}}.x}} {{ansible_lsb.codename}} main"
    - "deb-src https://deb.nodesource.com/{{node_{{node_version|split('.')[0]}}.x}} {{ansible_lsb.codename}} main"

- name: "Install the node.js package"
  apt:
    package: "nodejs"
    update_cache: yes
    state: present
