# file: nodejs/tasks/package.yml

- name: node.js | Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: node.js | add signing key
  apt_key:
    url: "{{nodejs_apt_key_url}}"
    id: "{{nodejs_apt_key}}"
    state: present

- name: node.js | add sources.list entry
  lineinfile:
    dest: /etc/apt/sources.list.d/nodesource.list
    create: yes
    line: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main"
    - "deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main"

- name: node.js | Install the node.js package
  apt:
    pkg: "nodejs={{ nodejs_version }}-1nodesource1~{{ ansible_lsb.codename }}1"
    update_cache: yes
    state: present
